### ISSUE TITLE
Ren'Py or other Engine Migration

### ISSUE THREAD

**Issue by ZeroPointNothing** [ZeroPointNothing/BatchQuest#12]
As Batch is not designed for what we are doing in any way whatsoever, I feel we should migrate this project over to something else, instead. Such as Ren'Py. This will require more training in this language for all people in the coding team, artists, and soundtrack people to complete.

- [ ] Soundtrack
- [ ] Artwork (Character, bacgkground, etc)
- [ ] Decent knowledgebase of Ren'py language
- [ ] New name for game (as it will no longer make sense to call it BatchQuest)

**Comment by Forestchild837** [comment]
Dont we already have flare for the soundtrack?

**Comment by ZeroPointNothing** [comment]
> Dont we already have flare for the soundtrack?

We do, yes. The checkmarks are when the things are _done._

**Comment by ZeroPointNothing** [comment]
> Possibly put a teensy price on the Ren'Py one, but leave this free. (emphasis on the possibly)

Just want to add, I say this because this is going to take a LOT more work. Especially if we make use of Ren'py's cutscene command.
